title: Lab 12
remote_theme: just-the-docs/just-the-docs

nav_external_links:
  - title: Conclusion
    url: lab11%20stream_data_pipeline_3_spark.html#conclusion
  
just_the_docs:
  custom_css:
    - assets/css/style.scss
    - assets/js/fix-links.js

